export type AlumniMember = {
  name: string
  note?: string
  image: string
}

export type AlumniCohort = {
  title: string
  season: string
  members: AlumniMember[]
}

export const alumniCohorts: AlumniCohort[] = [
  {
    title: '第一期学员',
    season: '同行者',
    members: [
      { name: 'Eliza', image: '/images/students/Eliza.jpg' },
      { name: 'IBU', image: '/images/students/IBU.jpg' },
      { name: 'Will', image: '/images/students/Will.jpg' },
      { name: 'WrongLei', note: '律师', image: '/images/students/WrongLei 律师.jpg' },
      { name: 'Zhan', image: '/images/students/Zhan.jpg' },
      { name: 'Weiweierbee', image: '/images/students/weiweierbee.jpg' },
      { name: '刘一洲', image: '/images/students/刘一洲.jpg' },
      { name: '刘林杰', image: '/images/students/刘林杰.jpg' },
      { name: '卜未鸣', image: '/images/students/卜未鸣.jpg' },
      { name: '卢思琦', image: '/images/students/卢思琦.jpg' },
      { name: '周芃芃', note: '律师', image: '/images/students/周芃芃律师.jpg' },
      { name: '宫致成', note: 'Robert', image: '/images/students/宫致成_Robert.jpg' },
      { name: '指针', image: '/images/students/指针.jpg' },
      { name: '李子豪', note: '君泽君', image: '/images/students/李子豪律师  「君泽君」.jpg' },
      { name: '林晓琳', image: '/images/students/林晓琳.jpg' },
      { name: '毛线球', image: '/images/students/毛线球。.jpg' },
      { name: '董远航', image: '/images/students/董远航.jpg' },
      { name: '郑玲珠', image: '/images/students/郑玲珠.jpg' }
    ]
  },
  {
    title: '第二期学员',
    season: '同行者',
    members: [
      { name: 'Wensley', image: '/images/students/Wensley.jpg' },
      { name: '陈可妮', image: '/images/students/陈可妮.jpg' },
      { name: '陈旸', image: '/images/students/陈旸.jpg' },
      { name: '丁铭', image: '/images/students/丁铭.jpg' },
      { name: '郭治年', image: '/images/students/郭治年.jpg' },
      { name: '郝韶泽', image: '/images/students/郝韶泽.jpg' },
      { name: '黄婉晴', image: '/images/students/黄婉晴.jpg' },
      { name: '老炊', image: '/images/students/老炊.jpg' },
      { name: '李震东', image: '/images/students/李震东.jpg' },
      { name: '林骥', image: '/images/students/林骥.jpg' },
      { name: '凌鹏飞', image: '/images/students/凌鹏飞.jpg' },
      { name: '刘佳馨', image: '/images/students/刘佳馨.jpg' },
      { name: '马骥一', image: '/images/students/马骥一.jpg' },
      { name: '毛依玲', image: '/images/students/毛依玲.jpg' },
      { name: '牛晓鑫', image: '/images/students/牛晓鑫.jpg' },
      { name: '钱驾浩', image: '/images/students/钱驾浩.jpg' },
      { name: '沈燕', image: '/images/students/沈燕.jpg' },
      { name: '苏成鹏', image: '/images/students/苏成鹏.jpg' },
      { name: '汪蓉', image: '/images/students/汪蓉.jpg' },
      { name: '王嘉璐', image: '/images/students/王嘉璐.jpg' },
      { name: '王静蕾', image: '/images/students/王静蕾.jpg' },
      { name: '王仲志', image: '/images/students/王仲志.jpg' },
      { name: '魏宏岩', image: '/images/students/魏宏岩.jpg' },
      { name: '邬晓霞', image: '/images/students/邬晓霞.jpg' },
      { name: '吴夙现', image: '/images/students/吴夙现.jpg' },
      { name: '徐海燕', image: '/images/students/徐海燕.jpg' },
      { name: '徐翔', image: '/images/students/徐翔.jpg' },
      { name: '徐幸杰', image: '/images/students/徐幸杰.jpg' },
      { name: '徐扬', image: '/images/students/徐扬.jpg' },
      { name: '许珩', image: '/images/students/许珩.jpg' },
      { name: '袁红姣', image: '/images/students/袁红姣.jpg' },
      { name: '章大成', image: '/images/students/章大成.jpg' },
      { name: '赵晖', image: '/images/students/赵晖.jpg' },
      { name: '郑姗儿', image: '/images/students/郑姗儿.jpg' },
      { name: '朱媛', image: '/images/students/朱媛.jpg' }
    ]
  },
  {
    title: '第三期学员',
    season: '同行者',
    members: [
      { name: 'Cathy', note: '王琳', image: '/images/students/Cathy（王琳）.jpg' },
      { name: 'KK', image: '/images/students/KK.jpg' },
      { name: 'Laughing', image: '/images/students/Laughing.jpg' },
      { name: 'outis', image: '/images/students/outis.jpg' },
      { name: '陈承正', image: '/images/students/陈承正.jpg' },
      { name: '陈乐永', image: '/images/students/陈乐永.jpg' },
      { name: '程婷', image: '/images/students/程婷.jpg' },
      { name: '崔佳杰', image: '/images/students/崔佳杰.jpg' },
      { name: '崔映西', image: '/images/students/崔映西.jpg' },
      { name: '方雁强', note: '律师', image: '/images/students/方雁强律师.jpg' },
      { name: '高旷', note: '海泰律师', image: '/images/students/高旷｜海泰律师.jpg' },
      { name: '庚利', note: 'GENG', image: '/images/students/庚利 GENG.jpg' },
      { name: '郭梦阳', image: '/images/students/郭梦阳.jpg' },
      { name: '胡碧莹', image: '/images/students/胡碧莹.jpg' },
      { name: '华占梅', image: '/images/students/华占梅.jpg' },
      { name: '霍兴瑞', note: '律师', image: '/images/students/霍兴瑞｜律师.jpg' },
      { name: '姜文涵', image: '/images/students/姜文涵.jpg' },
      { name: '卡皮巴拉蕾小姐', image: '/images/students/卡皮巴拉蕾小姐.jpg' },
      { name: '李书辉', image: '/images/students/李书辉.jpg' },
      { name: '李翔', image: '/images/students/李翔.jpg' },
      { name: '林晓青', note: '善执者行', image: '/images/students/林晓青.jpg' },
      { name: '凌寒', image: '/images/students/凌寒.jpg' },
      { name: '刘彬', note: '靖邦律所', image: '/images/students/刘彬律师丨靖邦律所.jpg' },
      { name: '柳彬', image: '/images/students/柳彬.jpg' },
      { name: '缪磊', image: '/images/students/缪磊.jpg' },
      { name: '潘涛', image: '/images/students/潘涛.jpg' },
      { name: '庞', note: '竞天宁波', image: '/images/students/庞（竞天宁波).jpg' },
      { name: '肉', image: '/images/students/肉.jpg' },
      { name: '沈炫汝', image: '/images/students/沈炫汝.jpg' },
      { name: '盛艺涵', image: '/images/students/盛艺涵.jpg' },
      { name: '苏', image: '/images/students/苏.jpg' },
      { name: '孙俊杰', image: '/images/students/孙俊杰.jpg' },
      { name: '孙玉涵', image: '/images/students/孙玉涵.jpg' },
      { name: '谭永欢', image: '/images/students/谭永欢.jpg' },
      { name: '王晓华', note: '海泰律师', image: '/images/students/王晓华【海泰律师】.jpg' },
      { name: '王元', note: '嘉源上海', image: '/images/students/王元-嘉源上海.jpg' },
      { name: '吴茂树', image: '/images/students/吴茂树.jpg' },
      { name: '小轩轩', note: 'Adam', image: '/images/students/小轩轩Adam.jpg' },
      { name: '谢凯', image: '/images/students/谢凯.jpg' },
      { name: '徐文涛', image: '/images/students/徐文涛.jpg' },
      { name: '阎慧鸣', image: '/images/students/阎慧鸣.jpg' },
      { name: '杨柳', note: '律师', image: '/images/students/杨柳律师.jpg' },
      { name: '姚静君', note: '海泰律师', image: '/images/students/姚静君 海泰律师.jpg' },
      { name: '叶凌男', image: '/images/students/叶凌男.jpg' },
      { name: '俞洁', image: '/images/students/俞洁.jpg' },
      { name: '袁中华', image: '/images/students/袁中华.jpg' },
      { name: '张锋', note: '律师', image: '/images/students/张锋律师.jpg' },
      { name: '张铭洋', note: '泰和泰律师', image: '/images/students/张铭洋 泰和泰律师.jpg' },
      { name: '张琦媛', image: '/images/students/张琦媛.jpg' },
      { name: '张庆鹏', image: '/images/students/张庆鹏.jpg' },
      { name: '张一一', image: '/images/students/张一一.jpg' },
      { name: '张禹行', image: '/images/students/张禹行.jpg' },
      { name: '郑权', note: '共业所', image: '/images/students/共业所郑权.jpg' },
      { name: '智慧', image: '/images/students/智慧.jpg' },
      { name: '周佳瑶', image: '/images/students/周佳瑶.jpg' },
      { name: '周亚', note: 'Lawyer · CPA · CTA', image: '/images/students/周亚.jpg' },
      { name: '朱兰兰', image: '/images/students/朱兰兰.jpg' }
    ]
  }
]
